
/*
 * This file was generated by the SOM Compiler.
 * FileName: C:\Misc\WPSProgramming\XShadow\Source\XShadow.h.
 * Generated using:
 *     SOM Precompiler somipc: 2.29.1.17
 *     SOM Emitter emith: 2.47
 */

/*
 *    XSHADOW.IDL
 * 
 *  =====================================================================#
 *                                                                       #
 *   CLASS: XShadow                                                      #
 *                                                                       #
 *   CLASS HIERARCHY:                                                    #
 *                                                                       #
 *       SOMObject                                                       #
 *         ÀÄÄ WPObject                                                  #
 *               ÀÄÄ WPShadow                                            #
 *                     ÀÄÄ XShadow                                       #
 *                                                                       #
 *   DESCRIPTION:                                                        #
 *                                                                       #
 *   Instances of this class are Workplace Shell objects.                #
 *                                                                       #
 *  =====================================================================#
 */


#ifndef SOM_XShadow_h
#define SOM_XShadow_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef XShadow
#define XShadow SOMObject
#endif
#include <wpshadow.h>

/*
 * Start of bindings for IDL types
 */

#ifndef SOMClass
    #define SOMClass SOMObject
#endif /* SOMClass */
#ifndef WPFolder
    #define WPFolder SOMObject
#endif /* WPFolder */
#ifndef M_WPObject
    #define M_WPObject SOMObject
#endif /* M_WPObject */
#ifndef WPObject
    #define WPObject SOMObject
#endif /* WPObject */
#ifndef WPImageFile
    #define WPImageFile SOMObject
#endif /* WPImageFile */
#ifndef M_WPAbstract
    #define M_WPAbstract SOMObject
#endif /* M_WPAbstract */
#ifndef M_WPShadow
    #define M_WPShadow SOMObject
#endif /* M_WPShadow */
#ifndef M_XShadow
    #define M_XShadow SOMObject
#endif /* M_XShadow */

/*
 * End of bindings for IDL types.
 */

#define XShadow_MajorVersion 1
#define XShadow_MinorVersion 3

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define XShadowNewClass c
#pragma linkage(c, system)
#define XShadowClassData d
#define XShadowCClassData x
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define XShadow_classObj XShadowClassData.classObject
#define _XShadow XShadow_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK XShadowNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(XShadowNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct XShadowClassDataStructure {
	SOMClass *classObject;
} SOMDLINK XShadowClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct XShadowCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK XShadowCClassData;

/*
 * New and Renew macros for XShadow
 */
#define XShadowNew() \
   ( _XShadow ? \
	_somNew(_XShadow) \
	: ( XShadowNewClass(\
		XShadow_MajorVersion, \
		XShadow_MinorVersion),\
	   _somNew(_XShadow)))
#define XShadowRenew(buf) \
   ( _XShadow ? \
	_somRenew(_XShadow, buf) \
	: ( XShadowNewClass(\
		XShadow_MajorVersion, \
		XShadow_MinorVersion),\
	   _somRenew(_XShadow, buf)))

/*
 * Override method: wpInitData
 */
#define XShadow_wpInitData(somSelf) \
	WPObject_wpInitData(somSelf)

/*
 * Override method: wpUnInitData
 */
#define XShadow_wpUnInitData(somSelf) \
	WPObject_wpUnInitData(somSelf)

/*
 * Override method: wpOpen
 */
#define XShadow_wpOpen(somSelf,hwndCnr,ulView,param) \
	WPObject_wpOpen(somSelf,hwndCnr,ulView,param)

/*
 * Override method: wpSetTitle
 */
#define XShadow_wpSetTitle(somSelf,pszNewTitle) \
	WPObject_wpSetTitle(somSelf,pszNewTitle)

/*
 * Override method: wpSetShadowTitle
 */
#define XShadow_wpSetShadowTitle(somSelf,pszNewTitle) \
	WPShadow_wpSetShadowTitle(somSelf,pszNewTitle)

/*
 * Override method: wpModifyPopupMenu
 */
#define XShadow_wpModifyPopupMenu(somSelf,hwndMenu,hwndCnr,iPosition) \
	WPObject_wpModifyPopupMenu(somSelf,hwndMenu,hwndCnr,iPosition)

/*
 * Override method: wpMenuItemSelected
 */
#define XShadow_wpMenuItemSelected(somSelf,hwndFrame,ulMenuId) \
	WPObject_wpMenuItemSelected(somSelf,hwndFrame,ulMenuId)

/*
 * Override method: wpMenuItemHelpSelected
 */
#define XShadow_wpMenuItemHelpSelected(somSelf,MenuId) \
	WPObject_wpMenuItemHelpSelected(somSelf,MenuId)

/*
 * Override method: wpCreateShadowObject
 */
#define XShadow_wpCreateShadowObject(somSelf,Folder,fLock) \
	WPObject_wpCreateShadowObject(somSelf,Folder,fLock)

/*
 * Override method: wpCopyObject
 */
#define XShadow_wpCopyObject(somSelf,Folder,fLock) \
	WPObject_wpCopyObject(somSelf,Folder,fLock)

/*
 * Override method: wpMoveObject
 */
#define XShadow_wpMoveObject(somSelf,Folder) \
	WPObject_wpMoveObject(somSelf,Folder)

/*
 * Override method: wpQueryTitle
 */
#define XShadow_wpQueryTitle(somSelf) \
	WPObject_wpQueryTitle(somSelf)

/*
 * Override method: wpSetStyle
 */
#define XShadow_wpSetStyle(somSelf,ulNewStyle) \
	WPObject_wpSetStyle(somSelf,ulNewStyle)

/*
 * Override method: wpQueryStyle
 */
#define XShadow_wpQueryStyle(somSelf) \
	WPObject_wpQueryStyle(somSelf)
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define XShadow_wpQueryShadowedObject WPShadow_wpQueryShadowedObject
#define XShadow_wpSetLinkToObject WPShadow_wpSetLinkToObject
#define XShadow_wpSetup WPObject_wpSetup
#define XShadow_wpSaveState WPObject_wpSaveState
#define XShadow_wpRestoreState WPObject_wpRestoreState
#define XShadow_wpFilterPopupMenu WPObject_wpFilterPopupMenu
#define XShadow_wpViewObject WPObject_wpViewObject
#define XShadow_wpCreateFromTemplate WPObject_wpCreateFromTemplate
#define XShadow_wpInsertPopupMenuItems WPObject_wpInsertPopupMenuItems
#define XShadow_wpInsertMenuItems WPObject_wpInsertMenuItems
#define XShadow_wpDragOver WPObject_wpDragOver
#define XShadow_wpDrop WPObject_wpDrop
#define XShadow_wpQueryDefaultHelp WPObject_wpQueryDefaultHelp
#define XShadow_wpConfirmDelete WPObject_wpConfirmDelete
#define XShadow_wpConfirmObjectTitle WPObject_wpConfirmObjectTitle
#define XShadow_wpPrintObject WPObject_wpPrintObject
#define XShadow_wpFormatDragItem WPObject_wpFormatDragItem
#define XShadow_wpDraggedOverObject WPObject_wpDraggedOverObject
#define XShadow_wpDroppedOnObject WPObject_wpDroppedOnObject
#define XShadow_wpQueryNameClashOptions WPObject_wpQueryNameClashOptions
#define XShadow_wpFilterMenu WPObject_wpFilterMenu
#define XShadow_wpModifyMenu WPObject_wpModifyMenu
#define XShadow_somDefaultInit SOMObject_somDefaultInit
#define XShadow_somDestruct SOMObject_somDestruct
#define XShadow_wpQueryHandle WPObject_wpQueryHandle
#define XShadow_wpSaveImmediate WPObject_wpSaveImmediate
#define XShadow_wpQueryIcon WPObject_wpQueryIcon
#define XShadow_wpQueryIconData WPObject_wpQueryIconData
#define XShadow_wpSetIconData WPObject_wpSetIconData
#define XShadow_wpReplaceObject WPObject_wpReplaceObject
#define XShadow_wpIdentify WPObject_wpIdentify
#define XShadow_wpAddObjectGeneralPage WPObject_wpAddObjectGeneralPage
#define XShadow_wpAddObjectGeneralPage2 WPObject_wpAddObjectGeneralPage2
#define XShadow_wpAddObjectWindowPage WPObject_wpAddObjectWindowPage
#define XShadow_wpAddSettingsPages WPObject_wpAddSettingsPages
#define XShadow_wpAddToObjUseList WPObject_wpAddToObjUseList
#define XShadow_wpAllocMem WPObject_wpAllocMem
#define XShadow_wpAppendObject WPObject_wpAppendObject
#define XShadow_wpAssertObjectMutexSem WPObject_wpAssertObjectMutexSem
#define XShadow_wpClose WPObject_wpClose
#define XShadow_wpCnrInsertObject WPObject_wpCnrInsertObject
#define XShadow_wpCnrRemoveObject WPObject_wpCnrRemoveObject
#define XShadow_wpCnrSetEmphasis WPObject_wpCnrSetEmphasis
#define XShadow_wpCopiedFromTemplate WPObject_wpCopiedFromTemplate
#define XShadow_wpCreateAnother WPObject_wpCreateAnother
#define XShadow_wpDelete WPObject_wpDelete
#define XShadow_wpDeleteFromObjUseList WPObject_wpDeleteFromObjUseList
#define XShadow_wpDisplayHelp WPObject_wpDisplayHelp
#define XShadow_wpDisplayMenu WPObject_wpDisplayMenu
#define XShadow_wpDoesObjectMatch WPObject_wpDoesObjectMatch
#define XShadow_wpEndConversation WPObject_wpEndConversation
#define XShadow_wpFindUseItem WPObject_wpFindUseItem
#define XShadow_wpFree WPObject_wpFree
#define XShadow_wpFreeMem WPObject_wpFreeMem
#define XShadow_wpHide WPObject_wpHide
#define XShadow_wpInsertSettingsPage WPObject_wpInsertSettingsPage
#define XShadow_wpQueryConcurrentView WPObject_wpQueryConcurrentView
#define XShadow_wpQueryButtonAppearance WPObject_wpQueryButtonAppearance
#define XShadow_wpQueryConfirmations WPObject_wpQueryConfirmations
#define XShadow_wpQueryDefaultView WPObject_wpQueryDefaultView
#define XShadow_wpQueryDetailsData WPObject_wpQueryDetailsData
#define XShadow_wpQueryError WPObject_wpQueryError
#define XShadow_wpSetFolder WPObject_wpSetFolder
#define XShadow_wpQueryFolder WPObject_wpQueryFolder
#define XShadow_wpQueryMinWindow WPObject_wpQueryMinWindow
#define XShadow_wpSetTaskRec WPObject_wpSetTaskRec
#define XShadow_wpFindTaskRec WPObject_wpFindTaskRec
#define XShadow_wpRegisterView WPObject_wpRegisterView
#define XShadow_wpReleaseObjectMutexSem WPObject_wpReleaseObjectMutexSem
#define XShadow_wpRender WPObject_wpRender
#define XShadow_wpRenderComplete WPObject_wpRenderComplete
#define XShadow_wpRequestObjectMutexSem WPObject_wpRequestObjectMutexSem
#define XShadow_wpRestore WPObject_wpRestore
#define XShadow_wpRestoreData WPObject_wpRestoreData
#define XShadow_wpRestoreLong WPObject_wpRestoreLong
#define XShadow_wpRestoreString WPObject_wpRestoreString
#define XShadow_wpSaveData WPObject_wpSaveData
#define XShadow_wpSaveDeferred WPObject_wpSaveDeferred
#define XShadow_wpSaveLong WPObject_wpSaveLong
#define XShadow_wpSaveString WPObject_wpSaveString
#define XShadow_wpScanSetupString WPObject_wpScanSetupString
#define XShadow_wpSetConcurrentView WPObject_wpSetConcurrentView
#define XShadow_wpSetButtonAppearance WPObject_wpSetButtonAppearance
#define XShadow_wpSetDefaultHelp WPObject_wpSetDefaultHelp
#define XShadow_wpSetDefaultView WPObject_wpSetDefaultView
#define XShadow_wpSetError WPObject_wpSetError
#define XShadow_wpQueryScreenGroupID WPObject_wpQueryScreenGroupID
#define XShadow_wpSetupOnce WPObject_wpSetupOnce
#define XShadow_wpSetIcon WPObject_wpSetIcon
#define XShadow_wpSetMinWindow WPObject_wpSetMinWindow
#define XShadow_wpModifyStyle WPObject_wpModifyStyle
#define XShadow_wpSwitchTo WPObject_wpSwitchTo
#define XShadow_wpQueryTrueStyle WPObject_wpQueryTrueStyle
#define XShadow_wpUnlockObject WPObject_wpUnlockObject
#define XShadow_wpObjectReady WPObject_wpObjectReady
#define XShadow_wpIsObjectInitialized WPObject_wpIsObjectInitialized
#define XShadow_wpCreateShadowObjectExt WPObject_wpCreateShadowObjectExt
#define XShadow_wpCnrDeleteUseItem WPObject_wpCnrDeleteUseItem
#define XShadow_wpIsDeleteable WPObject_wpIsDeleteable
#define XShadow_wpQueryCoreRecord WPObject_wpQueryCoreRecord
#define XShadow_wpSetObjectID WPObject_wpSetObjectID
#define XShadow_wpQueryObjectID WPObject_wpQueryObjectID
#define XShadow_wpSetDefaultIconPos WPObject_wpSetDefaultIconPos
#define XShadow_wpQueryDefaultIconPos WPObject_wpQueryDefaultIconPos
#define XShadow_wpCnrRefreshDetails WPObject_wpCnrRefreshDetails
#define XShadow_wpFindViewItem WPObject_wpFindViewItem
#define XShadow_wpLockObject WPObject_wpLockObject
#define XShadow_wpIsLocked WPObject_wpIsLocked
#define XShadow_wpQueryContainerFlagPtr WPObject_wpQueryContainerFlagPtr
#define XShadow_wpWaitForClose WPObject_wpWaitForClose
#define XShadow_wpSetMenuStyle WPObject_wpSetMenuStyle
#define XShadow_wpQueryMenuStyle WPObject_wpQueryMenuStyle
#define XShadow_somInit SOMObject_somInit
#define XShadow_somUninit SOMObject_somUninit
#define XShadow_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define XShadow_somDefaultAssign SOMObject_somDefaultAssign
#define XShadow_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define XShadow_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define XShadow_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define XShadow_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define XShadow_somDefaultVAssign SOMObject_somDefaultVAssign
#define XShadow_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define XShadow_somFree SOMObject_somFree
#define XShadow_somGetClass SOMObject_somGetClass
#define XShadow_somGetClassName SOMObject_somGetClassName
#define XShadow_somGetSize SOMObject_somGetSize
#define XShadow_somIsA SOMObject_somIsA
#define XShadow_somIsInstanceOf SOMObject_somIsInstanceOf
#define XShadow_somRespondsTo SOMObject_somRespondsTo
#define XShadow_somDispatch SOMObject_somDispatch
#define XShadow_somClassDispatch SOMObject_somClassDispatch
#define XShadow_somCastObj SOMObject_somCastObj
#define XShadow_somResetObj SOMObject_somResetObj
#define XShadow_somDispatchV SOMObject_somDispatchV
#define XShadow_somDispatchL SOMObject_somDispatchL
#define XShadow_somDispatchA SOMObject_somDispatchA
#define XShadow_somDispatchD SOMObject_somDispatchD
#define XShadow_somPrintSelf SOMObject_somPrintSelf
#define XShadow_somDumpSelf SOMObject_somDumpSelf
#define XShadow_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_XShadow_h */

#ifndef SOM_M_XShadow_h
#define SOM_M_XShadow_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef M_XShadow
#define M_XShadow SOMObject
#endif
/*
 *  New Class methods
 */
#include <wpshadow.h>

/*
 * Start of bindings for IDL types
 */


/*
 * End of bindings for IDL types.
 */

#define M_XShadow_MajorVersion 1
#define M_XShadow_MinorVersion 2

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define M_XShadowNewClass c
#pragma linkage(c, system)
#define M_XShadowClassData d
#define M_XShadowCClassData x
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define M_XShadow_classObj M_XShadowClassData.classObject
#define _M_XShadow M_XShadow_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK M_XShadowNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(M_XShadowNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct M_XShadowClassDataStructure {
	SOMClass *classObject;
	somMToken clsGetResourceModule;
	somMToken getHelpPath;
} SOMDLINK M_XShadowClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct M_XShadowCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK M_XShadowCClassData;

/*
 * New and Renew macros for M_XShadow
 */
#define M_XShadowNew() \
   ( _M_XShadow ? \
	_somNew(_M_XShadow) \
	: ( M_XShadowNewClass(\
		M_XShadow_MajorVersion, \
		M_XShadow_MinorVersion),\
	   _somNew(_M_XShadow)))
#define M_XShadowRenew(buf) \
   ( _M_XShadow ? \
	_somRenew(_M_XShadow, buf) \
	: ( M_XShadowNewClass(\
		M_XShadow_MajorVersion, \
		M_XShadow_MinorVersion),\
	   _somRenew(_M_XShadow, buf)))

/*
 * Override method: wpclsInitData
 */
#define M_XShadow_wpclsInitData(somSelf) \
	M_WPObject_wpclsInitData(somSelf)

/*
 * Override method: wpclsUnInitData
 */
#define M_XShadow_wpclsUnInitData(somSelf) \
	M_WPObject_wpclsUnInitData(somSelf)

/*
 * Override method: wpclsQueryStyle
 */
#define M_XShadow_wpclsQueryStyle(somSelf) \
	M_WPObject_wpclsQueryStyle(somSelf)

/*
 * Override method: wpclsQueryDefaultHelp
 */
#define M_XShadow_wpclsQueryDefaultHelp(somSelf,pHelpPanelId,pszHelpLibrary) \
	M_WPObject_wpclsQueryDefaultHelp(somSelf,pHelpPanelId,pszHelpLibrary)

/*
 * Override method: wpclsCreateDefaultTemplates
 */
#define M_XShadow_wpclsCreateDefaultTemplates(somSelf,Folder) \
	M_WPObject_wpclsCreateDefaultTemplates(somSelf,Folder)

/*
 * New Method: clsGetResourceModule
 */
typedef HMODULE   SOMLINK somTP_M_XShadow_clsGetResourceModule(M_XShadow *somSelf);
#pragma linkage(somTP_M_XShadow_clsGetResourceModule, system)
typedef somTP_M_XShadow_clsGetResourceModule *somTD_M_XShadow_clsGetResourceModule;
/*
 *  Resource Module handle
 */
#define somMD_M_XShadow_clsGetResourceModule "::M_XShadow::clsGetResourceModule"
#define M_XShadow_clsGetResourceModule(somSelf) \
    (SOM_Resolve(somSelf, M_XShadow, clsGetResourceModule) \
	(somSelf))
#ifndef SOMGD_clsGetResourceModule
    #if (defined(_clsGetResourceModule) || defined(__clsGetResourceModule))
        #undef _clsGetResourceModule
        #undef __clsGetResourceModule
        #define SOMGD_clsGetResourceModule 1
    #else
        #define _clsGetResourceModule M_XShadow_clsGetResourceModule
    #endif /* _clsGetResourceModule */
#endif /* SOMGD_clsGetResourceModule */

/*
 * New Method: getHelpPath
 */
typedef PSZ   SOMLINK somTP_M_XShadow_getHelpPath(M_XShadow *somSelf);
#pragma linkage(somTP_M_XShadow_getHelpPath, system)
typedef somTP_M_XShadow_getHelpPath *somTD_M_XShadow_getHelpPath;
/*
 *  Name of Help File
 *   attribute HMODULE  hmodResource; //# Resource module handle for XShadow
 */
#define somMD_M_XShadow_getHelpPath "::M_XShadow::getHelpPath"
#define M_XShadow_getHelpPath(somSelf) \
    (SOM_Resolve(somSelf, M_XShadow, getHelpPath) \
	(somSelf))
#ifndef SOMGD_getHelpPath
    #if (defined(_getHelpPath) || defined(__getHelpPath))
        #undef _getHelpPath
        #undef __getHelpPath
        #define SOMGD_getHelpPath 1
    #else
        #define _getHelpPath M_XShadow_getHelpPath
    #endif /* _getHelpPath */
#endif /* SOMGD_getHelpPath */
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define M_XShadow_wpclsQueryTitle M_WPObject_wpclsQueryTitle
#define M_XShadow_wpclsQueryIconData M_WPObject_wpclsQueryIconData
#define M_XShadow_wpclsQuerySetting M_WPAbstract_wpclsQuerySetting
#define M_XShadow_wpclsSetSetting M_WPAbstract_wpclsSetSetting
#define M_XShadow_wpclsObjectFromHandle M_WPObject_wpclsObjectFromHandle
#define M_XShadow_wpclsMakeAwake M_WPObject_wpclsMakeAwake
#define M_XShadow_wpclsNew M_WPObject_wpclsNew
#define M_XShadow_wpclsQueryDefaultView M_WPObject_wpclsQueryDefaultView
#define M_XShadow_wpclsQueryDetails M_WPObject_wpclsQueryDetails
#define M_XShadow_wpclsQueryDetailsInfo M_WPObject_wpclsQueryDetailsInfo
#define M_XShadow_wpclsQueryExtendedCriteria M_WPObject_wpclsQueryExtendedCriteria
#define M_XShadow_wpclsQueryFolder M_WPObject_wpclsQueryFolder
#define M_XShadow_wpclsQueryIcon M_WPObject_wpclsQueryIcon
#define M_XShadow_wpclsQuerySearchInfo M_WPObject_wpclsQuerySearchInfo
#define M_XShadow_wpclsFindObjectFirst M_WPObject_wpclsFindObjectFirst
#define M_XShadow_wpclsFindObjectNext M_WPObject_wpclsFindObjectNext
#define M_XShadow_wpclsFindObjectEnd M_WPObject_wpclsFindObjectEnd
#define M_XShadow_wpclsSetError M_WPObject_wpclsSetError
#define M_XShadow_wpclsQueryError M_WPObject_wpclsQueryError
#define M_XShadow_wpclsQuerySettingsPageSize M_WPObject_wpclsQuerySettingsPageSize
#define M_XShadow_wpclsQueryObject M_WPObject_wpclsQueryObject
#define M_XShadow_wpclsQueryButtonAppearance M_WPObject_wpclsQueryButtonAppearance
#define M_XShadow_wpclsDecUsage M_WPObject_wpclsDecUsage
#define M_XShadow_wpclsIncUsage M_WPObject_wpclsIncUsage
#define M_XShadow_wpclsInsertMultipleObjects M_WPObject_wpclsInsertMultipleObjects
#define M_XShadow_wpclsFindOneObject M_WPObject_wpclsFindOneObject
#define M_XShadow_wpclsSetSettingsPageSize M_WPObject_wpclsSetSettingsPageSize
#define M_XShadow_wpclsSetIconData M_WPObject_wpclsSetIconData
#define M_XShadow_wpclsSetIcon M_WPObject_wpclsSetIcon
#define M_XShadow_wpclsRemoveObjects M_WPObject_wpclsRemoveObjects
#define M_XShadow_somUninit SOMObject_somUninit
#define M_XShadow_somClassReady SOMClass_somClassReady
#define M_XShadow_somNew SOMClass_somNew
#define M_XShadow_somRenew SOMClass_somRenew
#define M_XShadow__get_somDataAlignment SOMClass__get_somDataAlignment
#define M_XShadow__get_somInstanceDataOffsets SOMClass__get_somInstanceDataOffsets
#define M_XShadow__get_somDirectInitClasses SOMClass__get_somDirectInitClasses
#define M_XShadow_somNewNoInit SOMClass_somNewNoInit
#define M_XShadow_somRenewNoInit SOMClass_somRenewNoInit
#define M_XShadow_somRenewNoZero SOMClass_somRenewNoZero
#define M_XShadow_somRenewNoInitNoZero SOMClass_somRenewNoInitNoZero
#define M_XShadow_somAllocate SOMClass_somAllocate
#define M_XShadow_somDeallocate SOMClass_somDeallocate
#define M_XShadow_somInitClass SOMClass_somInitClass
#define M_XShadow_somInitMIClass SOMClass_somInitMIClass
#define M_XShadow_somAddStaticMethod SOMClass_somAddStaticMethod
#define M_XShadow_somAddDynamicMethod SOMClass_somAddDynamicMethod
#define M_XShadow_somOverrideSMethod SOMClass_somOverrideSMethod
#define M_XShadow_somGetApplyStub SOMClass_somGetApplyStub
#define M_XShadow_somGetClassData SOMClass_somGetClassData
#define M_XShadow_somSetClassData SOMClass_somSetClassData
#define M_XShadow_somGetClassMtab SOMClass_somGetClassMtab
#define M_XShadow_somGetInstanceOffset SOMClass_somGetInstanceOffset
#define M_XShadow_somGetInstancePartSize SOMClass_somGetInstancePartSize
#define M_XShadow_somGetInstanceSize SOMClass_somGetInstanceSize
#define M_XShadow_somGetInstanceToken SOMClass_somGetInstanceToken
#define M_XShadow_somGetMemberToken SOMClass_somGetMemberToken
#define M_XShadow_somGetMethodData SOMClass_somGetMethodData
#define M_XShadow_somGetRdStub SOMClass_somGetRdStub
#define M_XShadow_somGetMethodDescriptor SOMClass_somGetMethodDescriptor
#define M_XShadow_somGetMethodIndex SOMClass_somGetMethodIndex
#define M_XShadow_somGetMethodToken SOMClass_somGetMethodToken
#define M_XShadow_somGetName SOMClass_somGetName
#define M_XShadow_somGetNthMethodData SOMClass_somGetNthMethodData
#define M_XShadow_somGetNthMethodInfo SOMClass_somGetNthMethodInfo
#define M_XShadow_somGetNumMethods SOMClass_somGetNumMethods
#define M_XShadow_somGetNumStaticMethods SOMClass_somGetNumStaticMethods
#define M_XShadow_somGetParent SOMClass_somGetParent
#define M_XShadow_somGetParents SOMClass_somGetParents
#define M_XShadow_somGetVersionNumbers SOMClass_somGetVersionNumbers
#define M_XShadow_somFindMethod SOMClass_somFindMethod
#define M_XShadow_somFindMethodOk SOMClass_somFindMethodOk
#define M_XShadow_somFindSMethod SOMClass_somFindSMethod
#define M_XShadow_somFindSMethodOk SOMClass_somFindSMethodOk
#define M_XShadow_somLookupMethod SOMClass_somLookupMethod
#define M_XShadow_somCheckVersion SOMClass_somCheckVersion
#define M_XShadow_somDescendedFrom SOMClass_somDescendedFrom
#define M_XShadow_somSupportsMethod SOMClass_somSupportsMethod
#define M_XShadow_somDefinedMethod SOMClass_somDefinedMethod
#define M_XShadow_somOverrideMtab SOMClass_somOverrideMtab
#define M_XShadow_somDefaultInit SOMObject_somDefaultInit
#define M_XShadow_somDestruct SOMObject_somDestruct
#define M_XShadow_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define M_XShadow_somDefaultAssign SOMObject_somDefaultAssign
#define M_XShadow_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define M_XShadow_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define M_XShadow_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define M_XShadow_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define M_XShadow_somDefaultVAssign SOMObject_somDefaultVAssign
#define M_XShadow_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define M_XShadow_somInit SOMObject_somInit
#define M_XShadow_somFree SOMObject_somFree
#define M_XShadow_somGetClass SOMObject_somGetClass
#define M_XShadow_somGetClassName SOMObject_somGetClassName
#define M_XShadow_somGetSize SOMObject_somGetSize
#define M_XShadow_somIsA SOMObject_somIsA
#define M_XShadow_somIsInstanceOf SOMObject_somIsInstanceOf
#define M_XShadow_somRespondsTo SOMObject_somRespondsTo
#define M_XShadow_somDispatch SOMObject_somDispatch
#define M_XShadow_somClassDispatch SOMObject_somClassDispatch
#define M_XShadow_somCastObj SOMObject_somCastObj
#define M_XShadow_somResetObj SOMObject_somResetObj
#define M_XShadow_somDispatchV SOMObject_somDispatchV
#define M_XShadow_somDispatchL SOMObject_somDispatchL
#define M_XShadow_somDispatchA SOMObject_somDispatchA
#define M_XShadow_somDispatchD SOMObject_somDispatchD
#define M_XShadow_somPrintSelf SOMObject_somPrintSelf
#define M_XShadow_somDumpSelf SOMObject_somDumpSelf
#define M_XShadow_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_M_XShadow_h */
